---
date: '`r format(Sys.time(), "%B %d, %Y")`'
## Author Details
return-address:
  - Vollveien 7,
  - 1433, Ås
  - NORWAY
author:
  - Raju Rimal
## To whome you are writing
address: 
  - Romà Tauler,
  - Editor in Chief
  - Chemometrics and Intelligent Laboratory Systems
## Opening of Letter
opening: Dear Mr. Tauler,
## Closing of Letter
closing: Sincerely,
## Other template variables
fontsize: 11pt
linestretch: 1.15
geometry: margin=1in
blockquote: true
signature-space: 1.5cm
closing-indentation: 0pt
links-as-notes: true
colorlinks: true
papersize: a4
fontfamily: mathpazo
output: linl::linl
---

```{r, echo = FALSE, message=FALSE, warning=FALSE}
library(RefManageR)
bib <- ReadBib("../ref-db.bib")
```

I am pleased to submit an original research article entitled "**Comparison of Multi-response Prediction Methods**" on behalf of the authors. This manuscript has made an extensive comparison of different multivariate multi-response prediction methods including Principal Component Regression, Partial Least Squares Regression and Envelopes. The data are simulated based on a factorial design of various properties of data that includes the predictors components relevant for the response and levels of multicollinearity in the predictors. The manuscript also demonstrate an application of the tool _simrel_ ^[`r paste(substring(capture.output(bib["Rimal2018"]), 5), collapse = "")`] which we have discussed in the previous paper published in Chemometrics and Intelligent Laboratory System. 

Many multivariate regression methods have been developed but only few of them have leveraged the covariance structure of response variables for prediction. Here we have compared well established methods such as Principal Components Regression and Partial Least Square Regression with Envelopes which is relatively new and claimed to have better performance. The comparison is made using both simulated and the real data from the field of chemometrics.

This manuscript not only gives an overview on the performance of these prediction methods but also encourages researchers to explore, use and implement newly developed methods based on the properties of their data. We believe that this manuscript is appropriate for publication in _Research Paper_ section in Chemometrics and Intelligent Laboratory System.

This manuscript has not been published and is not under consideration for publication elsewhere. We have no conflict of interest to disclose.

Thank you for your consideration.
