# Discussions and Conclusion

Analysis with both simulated data and real data have shown that the envelope methods are more stable, less influenced by `relpos` and `gamma` and are in general performed better than PCR and PLS methods. These methods are also found to be less dependent on the number of components. Observing data in fewer and relevant dimension is an advantage for many discipline as well.

Since each facets in the Figure \@ref(fig:pred-pca-hist-mthd-gamma-relpos) and \@ref(fig:comp-pca-hist-mthd-gamma-relpos) have own scales, despite having some large prediction error seen at the right tail, envelope methods still have less prediction error and have used fewer number of components than the others.

Particularly in the case of simultaneous envelope, since users can specify the number of dimension for response envelope, the method can leverage the relevant space of response while PCR, PLS and Xenv are constrained to play only on predictor space. Since the simulation is based on single latent component of the response variables, this might have given some advantage for simultaneous envelope.

Further, we have fixed the coefficient of determination ($R^2$) constant throughtout all the designs. Initial simulations (not shown) indicated that low $R^2$ affect all methods in similar manner and the MANOVA is hightly dominated by $R^2$. Keeping the value of $R^2$ fixed has allowed us to analyze other factors properly.

Two clear comment can be made about the effect of correlation of response on the prediction methods. Highly correlated response has shown highest prediction error in general and the effect is most distinct in envelope methods. Since the envelope methods identifies the relevant space as the span of relevant eigenvectors, the methods are able to obtain the minimum average prediction error by using fewer number of components for all levels of `eta`.

As of our knowledge, the effect of correlation in the response on PCR and PLS methods are less explored. In this regards, it is interesting to see that these methods have used large number of components and returned large prediction error than envelope methods in the case of highly correlated responses. In order to fully understand the effect of `eta`, it is necessary to study the estimation performance of these methods at different number of components.

In addition, since using principal components or actual variables as predictors in envelope methods have shown similar results, we have used principal components that have explained 97.5% of the variation as mentioned previously in the cases of envelope methods for the designs where $p>n$. As the envelope methods are based on MLE and this can be an alternative way of using the methods in data with wide predictors. The results from this study will help researcher to understand these methods for different nature of data. We encourage researcher to use newly developed methods such as envlope based on the nature of data they are working on.

Since, this study have focused entirely on prediction performance, further analysis of their estimative properties of these methods is required. A study of estimation error and the behaviour of methods on non-optimal number of components can give deeper understanding of these methods.

A shiny application [@shiny] is availiable at [http://therimalaya.shinyapps.io/Comparison](http://therimalaya.shinyapps.io/Comparison) where all the results related to this study can be visualized. In addition, a github repository at [https://github.com/therimalaya/03-prediction-comparison](https://github.com/therimalaya/03-prediction-comparison) can be used to reproduce this study.

# Acknowledgment
We are grateful to Inge Helland on his inputs on this paper throughout the period. His guidance on the envelope models and review on this paper helped us to shape this paper extensively. We would gratefully like to thank Kristian Lillan, Ulf Indahl, Tormod Næs, Ingrid Måge and the team for providing the data for analysis.
